# Build
FROM golang:1.25 as build
WORKDIR /app
COPY 1_primetime/primetime.go 1_primetime/go.mod ./
COPY server ../server
RUN CGO_ENABLED=0 go build -o primetime .

# Run
FROM scratch
WORKDIR /app
COPY --from=build /app/primetime .
EXPOSE 8080
CMD ["./primetime"]