# Build
FROM golang:1.25 as build
WORKDIR /app
COPY 0_smoketest/smoketest.go 0_smoketest/go.mod ./
COPY server ../server
RUN CGO_ENABLED=0 go build -o smoketest .

# Run
FROM scratch
WORKDIR /app
COPY --from=build /app/smoketest .
EXPOSE 8080
CMD ["./smoketest"]