# Build
FROM golang:1.25 as build
WORKDIR /app
COPY 4_unusual_database_program/ ./
COPY server ../server
RUN CGO_ENABLED=0 go build -o unusual_database_program .

# Run
FROM scratch
WORKDIR /app
COPY --from=build /app/unusual_database_program .
EXPOSE 8080
CMD ["./unusual_database_program"]