# Build
FROM golang:1.25 as build
WORKDIR /app
COPY 5_mob_in_the_middle/ ./
COPY server ../server
RUN CGO_ENABLED=0 go build -o mob_in_the_middle .

# Run
FROM scratch
WORKDIR /app
COPY --from=build /app/mob_in_the_middle .
EXPOSE 8080
CMD ["./mob_in_the_middle"]